[package]
name = "workspaces"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = "0.1"
anyhow = "1.0"
base64 = "0.13"
chrono = "0.4.19"
dirs = "3.0.2"
hex = "0.4.2"
portpicker = "0.1.1"
rand = "0.8.4"
reqwest = { version = "0.11", features = ["json"] }
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-retry = "0.3"
url = { version = "2.2.2", features = ["serde"] }

near-crypto = { git = "https://github.com/near/nearcore", rev = "88a9e74d4b99867e417fe199cbd74559fd4fc349" }
near-primitives = { git = "https://github.com/near/nearcore", rev="88a9e74d4b99867e417fe199cbd74559fd4fc349" }
near-jsonrpc-primitives = { git = "https://github.com/near/nearcore", rev="88a9e74d4b99867e417fe199cbd74559fd4fc349" }

near-sandbox-utils = { git = "https://github.com/near/sandbox" }

[dependencies.near-jsonrpc-client]
git = "https://github.com/near/near-jsonrpc-client-rs"
rev = "d3c7a057792f661ba585b575012bf85d954bd327"
features = ["sandbox"]
